controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    pos_controller:
      type: position_controllers/JointGroupPositionController

    vec_controller:
      type: velocity_controllers/JointGroupVelocityController

    tau_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pos_controller:
  ros__parameters:
    joints:
      - knee_pitch_joint
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
      - effort

vec_controller:
  ros__parameters:
    joints:
      - knee_pitch_joint
    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity
      - effort

tau_controller:
  ros__parameters:
    joints:
      - knee_pitch_joint
    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort